- docs/annotations.md
- pkg/api/annotations/pod.go
- pkg/nodeclient/itzoclient.go
- pkg/server/cloud/aws/aws.go
- pkg/server/cloud/aws/instances.go
- pkg/server/cloud/aws/network.go
- pkg/server/cloud/azure/network.go
- pkg/server/cloud/cloud.go
- pkg/server/cloud/mock.go
- pkg/server/config.go
- pkg/server/convert.go
- pkg/server/server.go
The most noticeable change/rename is moving `ControllerInsideVPC()` out of the `CloudClient` interface. It has been replaced with `ConnectWithPublicIPs()` which is all we were using `ControllerInsideVPC()` for anyways.
At the last minute I also added the `pod.elotl.co/private-ip-only` annotation to allow users to not have a public IP address on their cells. This required re-working the node client to fall back to a private address when a public address isn't available.  It's up to the user to setup VPC endpoints or some other system to download itzo and images (e.g. they could run a private registry and download itzo from an instance located in the subnet).
There's a bit more logging here and there but I think it's for the best, it only shows up when the controller is starting up and …
> connect to private IPs if cell subnet has no internet gateway

- cmd/virtual-kubelet/main.go
This is a pretty trivial one. At one point we pinned our k8s dependencies to v1.17.0, but did not update k8sversion in main.go then. This should have VK report its version prefix as v1.17.0-vk instead of v1.14.0-vk.
> Update reported k8s version in main.go

- deploy/terraform/main.tf
- pkg/server/cloud/aws/network.go
- pkg/server/cloud/azure/network.go
- pkg/server/cloud/cloud.go
- pkg/server/cloud/mock.go
- pkg/server/pod_controller.go
- pkg/util/network.go
- pkg/util/network_test.go
Instead of using resolv.conf from the host, query the cloud API on DNS
info such as nameservers and the DNS search list. Kip might be running a
in different network, outside of the pod VPC, with DNS configuration
that might not work inside the VPC.
> Query cloud for DNS info

- pkg/server/pod_controller.go
- pkg/server/registry/common.go
- pkg/server/registry/pod_registry.go
This makes sure we don't keep pods in our registry after the user deletes them, thus they can be recreated right away in the same namespace with the same name.
I also added some extra checks to pod updates in the registry.
> Make pod deletion synchronous

- pkg/server/convert.go
- pkg/server/convert_test.go
- pkg/server/pod_controller_utils.go
When a pod or cell fails in kip, the pod should behave similarly to a pod/container failing in kubelet.  The pod should be restarted on a new cell, similar to a container being recreated (depending on the pod's restart policy)
In k8s, if a pod enters into a terminal state, it never leaves that state.  To deal with this, lets reset a failed pod back to `Pending` in k8s if the pod will be restarted by kip.
> fix up pod phase: reset to Pending when kip pod should be restarted

- cmd/virtual-kubelet/flags.go
- cmd/virtual-kubelet/main.go
- deploy/terraform-vpn/kustomization/deployment.yaml.tmpl
- deploy/terraform-vpn/kustomization/kustomization.yaml.tmpl
- deploy/terraform-vpn/kustomization/node-local-dns.yaml.tmpl
- deploy/terraform-vpn/main.tf
- deploy/terraform-vpn/variables.tf
- docs/annotations.md
- pkg/api/annotations/pod.go
- pkg/api/validation/validation.go
- pkg/server/cloud/aws/network.go
- pkg/server/cloud/azure/network.go
- pkg/server/cloud/cloud.go
- pkg/server/cloud/mock.go
- pkg/server/deploy_util.go
- pkg/server/garbage_controller.go
- pkg/server/helpers.go
- pkg/server/nodemanager/node_controller.go
- pkg/server/nodemanager/node_controller_test.go
- pkg/server/pod_controller.go
- pkg/server/server.go
Changes:
- New `pod.elotl.co/cloud-route: <cidr1 cidr2 ...>` annotation, that will make Kip add a route in the cloud subnet route table, using the instance backing the pod as the next hop for the CIDRs.
- I refactored the setup for DNS and how the network agent token is created, to reduce clutter in the pod controller, and injecting them as PodController dependencies.
- I threaded through the `--cluster-domain` parameter from node-cli, so the cluster domain can now be overridden.
- Added a `--cluster-dns` parameter to make the DNS used by pods with a `ClusterFirst` DNS policy configurable.
The main use case right now is to allow a caching DNS server in the VPC subnet for a hybrid on-prem/cloud setup: the caching DNS pod can add a route to its extra IP address (e.g. node-local-dns has a …
> Add annotation for creating pod cloud routes

- Gopkg.lock
- Gopkg.toml
- pkg/server/getcontainerlogs.go
- vendor/github.com/virtual-kubelet/virtual-kubelet/node/api/exec.go
- vendor/github.com/virtual-kubelet/virtual-kubelet/node/api/helpers.go
- vendor/github.com/virtual-kubelet/virtual-kubelet/node/api/logs.go
- vendor/github.com/virtual-kubelet/virtual-kubelet/node/api/server.go
- vendor/github.com/virtual-kubelet/virtual-kubelet/node/pod.go
Now that https://github.com/virtual-kubelet/virtual-kubelet/pull/806 has been merged, we can improve how getting container logs behaves:
- Support for `-f`.
- Same default options as kubelet (getting all logs by default).
> Pull in logs changes from VK

- pkg/server/server.go
The pod status notifier callback should only be called when the pod
status has changed in Kip, and not from any VK API method. VK can't
handle asynchronous status updates that come from an API method it's
calling in Kip.
> Fix pod status updates

- deploy/terraform/main.tf
- deploy/terraform/outputs.tf
- deploy/terraform/variables.tf
This adds the ability to create an EFS filesystem and mount target on AWS when using the TF example, so cells and pods have access to a simple storage option. I kept it disabled by default.
The main use case for now is to enable cells to cache images, speeding up subsequent pod starts. Right now one can add a cloud init file that will have cells mount in the EFS volume under /tmp/tosi (or symlink it there), effectively sharing an image cache for all pods. Note: this use case relies on https://github.com/elotl/tosi/pull/6; the current AMIs have an older version of tosi.
> Add EFS support to TF example

- pkg/server/cloud/aws/aws_functional_test.go
- pkg/server/cloud/aws/instances.go
- pkg/server/cloud/azure/azure_functional_test.go
- pkg/server/cloud/azure/instances.go
- pkg/server/cloud/cloud.go
- pkg/server/cloud/functional/functional_test_template.go
- pkg/server/cloud/mock.go
- pkg/server/config.go
- pkg/server/nodemanager/node_controller.go
- pkg/server/nodemanager/node_controller_test.go
- pkg/server/nodemanager/node_scaler.go
In the AWS backend, "xvda" is hardcoded when we call RunInstances(). However, the name of the root device depends on the AMI. We need to check and save RootDeviceName from DescribeImages(), and use it when creating a new instance.
This fixes #83
> Save root device name when looking up image

- deploy/manifests/virtual-kubelet/base/deployment.yaml
- deploy/manifests/virtual-kubelet/base/sa.yaml
- scripts/init-cert/Dockerfile
- scripts/init-cert/csr/create-csr.sh
- scripts/init-cert/csr/csr.conf
- scripts/init-cert/csr/csr.yaml
- scripts/init-cert/csr/get-cert.sh
I added a simple init container to VK that generates a server certificate for serving the API. Unfortunately, we have to jump through a few extra hoops (approving the CSR ourselves) since VK uses its own service account for interacting with the control plane.
I made sure the certificate is only generated if it's missing or invalid.
> Generate server certificate in an init container

- Makefile
- pkg/server/server.go
Two changes:
- I added some V(5) logs when the provider is being created.
- In Makefile, one can now use the `DKR` environment variable to choose `img`, `docker` or any other command line compatible client for building and pushing the kip image, e.g. `make img DKR=docker` will build the image via docker.
> Add more debug logging when creating provider

- pkg/server/convert.go
- pkg/server/pod_controller.go
- pkg/server/pod_controller_test.go
K8s docs for image pull specs are here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
This is a first pass at being able to use image pull secrets created with kubectl.  It's not perfect (I think docker's config.json allows you to specify different creds for the same repo URL at different paths) but it's a decent start.
Creating docker secrets:
```bash
$ kubectl create secret docker-registry regcred \
--docker-server=<server> \
--docker-username=<username> \
--docker-password=<password> \
--docker-email=<docker-email>
$kubectl create secret generic file-regcred \ 
--from-file=.dockerconfigjson=/home/myuser/.docker/config.json \
--type=kubernetes.io/dockerconfigjson
```
The first case creates a secret detailed here: …
> fix up using imagePullSecrets in kip, be able to use dockerconfigjson

- pkg/server/cloud/gce/metadata.go
- pkg/server/cloud/gce/metadata_test.go
- pkg/server/cloud/gce/network.go
For some reason, when you curl the gce metadata service for the zone, from alpine, an extra slash gets added to the response:
```bash
exec -it curler -- /bin/ash
projects/832569367454/zones/us-west1-a/
```
This does not happen in other distros (debian and ubuntu were tested)
```
kk exec -it curler -- curl "http://metadata.google.internal/computeMetadata/v1/instance/zone" -H "Metadata-Flavor: Google"
projects/832569367454/zones/us-west1-a
```
The library we use assumes the response doesn't end with a slash and it'll break if it does end in a slash.  This PR gets the zone from the metadata ourselves and handle both cases.
> Handle broken metadata response in google cloud

- deploy/terraform-gcp/main.tf
- docs/provider-config.md
- pkg/server/config.go
- pkg/server/nodemanager/node_controller.go
- pkg/server/server.go
- pkg/util/cloudinitfile/cloudinitfile.go
Two changes:
- A new config file parameter, `cells.cellConfig`. This is a map[string]string, and it will be serialized and sent to the instance via as a cloud-init file `/tmp/itzo/cell_config.yaml`. Agents on the instance can read it in, and get configuration data from the entries. Right now it's used for providing image-cache configuration parameters.
- A small fix to ensure manifests are re-deployed in terraform-gcp when the cluster ID changes.
> Add cells.cellConfig

- docs/provider-config.md
- pkg/server/cloud/aws/aws.go
- pkg/server/cloud/aws/aws_functional_test.go
- pkg/server/cloud/gce/network.go
- pkg/server/cloud/gce/option.go
- pkg/server/config.go
There are 2 changes in this one:
1. Refactor `NewEC2Client()` to take a config structure instead of an arguments list. I took that strategy from virtual-kubelet and like it because, for long argument lists, there's less chance you're going to pass in the wrong arg in the wrong place. You can also leave things empty if you want them to remain unspecified.
2. A new provider.yaml option that allows the user to turn off using public IP addresses for the entire controller.  I think this will be the default setting for most production systems.  I made it a pointer value so we can determine if the user left the value unspecified vs. setting it to false.  We can eventually decide what the default/unspecified value should be.
I also added a minor fix to the DNS configuration in GCE. The search …
> provider.yaml flag to force cells to never have a public IP

- Dockerfile
- pkg/server/cloud/gce/gce.go
- pkg/server/cloud/gce/instances.go
- pkg/server/cloud/gce/metadata.go
- pkg/server/cloud/gce/network.go
- pkg/server/cloud/gce/option.go
This adds the following GKE instance metadata keys present on the virtual-kubelet node to the instance metadata of Kip Cells:
- cluster-location
- cluster-name
- cluster-uid
After these were added, DaemonSet Pods now start up and run but with errors about service accounts in the logs.
I also cleaned up initialization of our gceClient and did a minor commit to change the order layers are created in our Dockerfile.
> Bcox gke metadata

- deploy/terraform/main.tf
- deploy/terraform/node.sh
- pkg/server/getstatssummary.go
This is the time when the pod or container was started, not the timestamp of the first sample we have in memory (which is a moving window of samples).
> Fix StartTime in pod and container stats

- deploy/manifests/virtual-kubelet/base/deployment.yaml
- deploy/terraform-gcp/env.tfvars.example
- deploy/terraform-gcp/variables.tf
- pkg/server/cloud/gce/network.go
This will have the GCP Terraform config auto-allocate the service and pod CIDRs by default, so there will be no range collision when multiple users provision clusters in the same project/network.
I also reduced the default CPU request for the VK deployment to make sure it fits into an n1-standard-1 instance. With the default system pods, it's close to being full on GKE.
> Auto-allocate CIDRs on GCP

- pkg/server/cloud/gce/gce.go
- pkg/server/cloud/gce/instances.go
- pkg/server/cloud/gce/option.go
We plan to run a monitoring and a logging agent on GCE instances to
better integrate with stackdriver. This adds the necessary scopes so
that those agents can send data to SD.
> Add logging.write and monitoring.write scopes to GCE instances

- scripts/init-cert/Dockerfile
- scripts/init-cert/build.sh
Since init-cert uses kubectl, we need to ensure the right version is
used (kubectl guarantees one minor version skew compatibility).
I added a script to build multiple images for each Kubernetes version
between 1.12 and 1.18. Depending on the cluster, the use can simply
change the image to e.g. elotl/init-cert:k8s-1.14 in a 1.14.x cluster.
> Build multiple init-cert images

- pkg/server/cloud/mock.go
- pkg/server/config.go
- pkg/server/server.go
If MOCK_CLOUD_API=true (or some variation of true) then run kip with a mocked out cloud provider.  To do this, I've added a couple more fake methods in the cloud mock.
One caveat of this change is that the user cannot run with the mock cloud provider and then, using the same persistent volume, change to running with a regular cloud provider.  That will cause issues with the code that detects a region change.  While it's unlikely a user would change regions in kip (it was an easy change to make in milpa's configuration), I still think we should catch that.  There are ways around this issue but I think we don't need to implement them at this time.
> GCE Marketplace: env var to run kip using the mock cloud provider

- deploy/terraform-gcp/main.tf
This way the user does not need to configure their GCE service account
credentials via provider.yaml. In fact, the whole GCE section can be
left empty:
cloud:
gce: {}
and Kip will auto-detect everything.
> Add compute scope to GKE node pool in TF

- .travis.yml
Using `-u` with go get will try to update dependencies, and it seems a minor version change broke something in one of them, making the installation of deepcopy-gen fail. Removing `-u` fixes the problem.
> Fix deepcopy-gen install

- .travis.yml
- README.md
- deploy/manifests/kip/README.md
- deploy/manifests/kip/base/kustomization.yaml
- deploy/manifests/kip/base/network-agent.yaml
- deploy/manifests/kip/base/pvc.yaml
- deploy/manifests/kip/base/sa.yaml
- deploy/manifests/kip/base/statefulset.yaml
- deploy/manifests/kip/overlays/cloudinit/kustomization.yaml
- deploy/manifests/kip/overlays/cloudinit/statefulset.yaml
- deploy/manifests/kip/overlays/conformance-tests/kustomization.yaml
- deploy/manifests/kip/overlays/gcp/kustomization.yaml
- deploy/manifests/kip/overlays/minikube/kustomization.yaml
- deploy/manifests/kip/overlays/minikube/statefulset.yaml
- deploy/terraform-aws/README.md
- deploy/terraform-aws/main.tf
- deploy/terraform-aws/node.sh
- deploy/terraform-gcp/README.md
- deploy/terraform-gcp/main.tf
- deploy/terraform-vpn/README.md
- deploy/terraform-vpn/kustomization/kustomization.yaml.tmpl
- deploy/terraform-vpn/kustomization/node-local-dns.yaml.tmpl
- deploy/terraform-vpn/kustomization/vpn-deployment.yaml.tmpl
- deploy/terraform-vpn/main.tf
- deploy/terraform-vpn/variables.tf
- scripts/run_smoke_test.sh
The goal is to make it easier to override parameters that apply to every resource we deploy, such as the namespace, name prefixes and suffixes.
Note: unfortunately, we can't use `kubectl kustomize` or `kubectl apply -k` anymore, since it comes with an old version of kustomize built in. I added kustomize to our build, and also updated our docs.
> Refactor templates

- .travis.yml
- Makefile
- scripts/init-cert/Dockerfile
- scripts/init-cert/build.sh
- scripts/init-cert/kubectl.sh
- scripts/run_smoke_test.sh
- scripts/update_latest_tags.sh
Changes:
- Build only one init-cert image, with all supported kubectl versions included. One that is compatible with the server is chosen during runtime.
- Have the build create and use an init-cert image, instead of pulling an existing one from the registry.
- If all tests pass, and the build is for a release tag in git, update the :latest tag for elotl/kip and elotl/init-cert.
> Create init-cert image in build, and update latest tags after tests

- README.md
- deploy/manifests/kip/overlays/gcp/provider.yaml
- deploy/terraform-gcp/README.md
- deploy/terraform-gcp/variables.tf
- docs/provider-config.md
- pkg/server/cloud/gce/network.go
Kip can use the service account credentials on its host instance. Updating manifests and docs to reflect this.
1. If deploying via terraform, change the default kustomize base to GCE and default to pulling credentials from the host instance.
2. If adding kip to an existing k8s cluster, update the docs to talk about 2 ways of authenticating (similar to AWS)
Also updated docs/provider-yaml.md to have a blurb about GCE cloud configuration.
> updating docs and manifests for deploying into GCE

- deploy/terraform-aws/node.sh
Instead of fetching the key and then adding it to apt, which has been
flaky lately, fetch it from a keyserver. This should help with smoke
test flakyness.
> Fetch GPG key from keyserver

- docs/provider-config.md
- pkg/server/cloud/aws/aws.go
- pkg/server/config.go
Addresses the point in issue in https://github.com/elotl/kip/issues/141.  Allow the user to specify a custom endpoint URL used by the ec2 client.  This overrides the default behavior of connecting to the endpoint at `protocol://service-code.region-code.amazonaws.com` (see: https://docs.aws.amazon.com/general/latest/gr/rande.html).
Also get rid of the unused AWS ELB Client (from the old Milpa days).
> allow user to specify endpointURL in provider.yaml. 

- deploy/manifests/kip/base/statefulset.yaml
If a user pipes the generated manifests through envsubst, then any un-escaped variable will be substituted. I changed the statefulset manifest to use Kubernetes-style escaping to prevent it.
> Use k8s-style escaped envvar in manifest

- pkg/server/cloud/aws/aws.go
- pkg/server/config.go
This helps if Kip is running inside a VPC. In the basic case, now the user can simply use:
cloud:
aws: {}
in their provider.yaml.
> Autodetect AWS region

- pkg/util/instanceselector/gce_instance_data.go
- pkg/util/instanceselector/instanceselector_test.go
- scripts/create_instance_data/create_gce_instance_data.py
Updated e2 custom instance data to start at 2 cpus.  Also updated the instance data for GCE. Seems like some regions added additional e2 (`e2-highcpu-32`, `e2-standard-32`, etc) instance types.
> e2 custom instances start with 2 cpus, updated GCE instance data

- docs/provider-config.md
- pkg/server/cloud/aws/instances.go
- pkg/server/cloud/azure/instances.go
- pkg/server/cloud/cloud.go
- pkg/server/cloud/gce/instances.go
- pkg/server/cloud/mock.go
- pkg/server/config.go
- pkg/server/pod_controller.go
- pkg/server/server.go
In provider.yaml, cells.defaultIAMPermissions specifies the a cloud-specific IAM permission that will be added to cell instances. On AWS, this is an IAM instance profile, and can be overridden by the pod.elotl.co/instance-profile pod annotation.
> Add cells.defaultIAMPermissions to provider.yaml

- scripts/init-cert/csr/get-cert.sh
- scripts/init-cert/kubectl.sh
The kubectl wrapper will write some extra output if it can't find a kubectl client that matches the version from the API server, which will interfere with commands in init-cert that pipe its output into another command. I removed the line causing the extra output.
Other changes:
* Check existing certificate for both hostname and SAN IP address.
* Use functions for code where we're waiting until a timeout.
> Fix extra output from kubectl

- docs/kip-iam-permissions.md
- pkg/server/cloud/aws/aws_functional_test.go
- pkg/server/cloud/aws/ecr.go
- pkg/server/cloud/aws/ecr_test.go
- pkg/server/cloud/azure/azure.go
- pkg/server/cloud/cloud.go
- pkg/server/cloud/functional/functional_test_template.go
- pkg/server/cloud/gce/gce.go
- pkg/server/cloud/mock.go
- pkg/server/pod_controller.go
ECR Registry credentials are issued regionally.  Update Kip to create creds in the region the image is stored in.
> Bcox ecr multi region

- .gitignore
- deploy/terraform-aws/env.tfvars.example
- deploy/terraform-aws/main.tf
- deploy/terraform-aws/variables.tf
- deploy/terraform-gcp/main.tf
- deploy/terraform-vpn/main.tf
Fix[ issue 153](https://github.com/elotl/kip/issues/153).
Testing done: ran `terraform apply` and `terraform destroy` with the fix and did not see the warning.
```
$ terraform destroy -var-file myenv.tfvars 
data.external.manifest: Refreshing state...
random_id.k8stoken-suffix: Refreshing state... [id=MX9JLw3fzGc]
random_id.k8stoken-prefix: Refreshing state... [id=3IUc]
data.template_file.node-userdata: Refreshing state...
data.aws_availability_zones.available-azs: Refreshing state...
aws_vpc.main: Refreshing state... [id=vpc-0f1c0e5960fe4f403]
aws_iam_role.k8s-node: Refreshing state... [id=k8s-node-myechuri-argo-cluster]
data.aws_ami.ubuntu: Refreshing state...
aws_iam_instance_profile.k8s-node: Refreshing state... [id=k8s-node-myechuri-argo-cluster]
aws_iam_role_policy.k8s-node: …
```
> Fix terraform warning from deploy/terraform-aws

- pkg/server/cloud/aws/aws_functional_test.go
- pkg/server/cloud/functional/functional_test_template.go
- pkg/server/cloud/gce/firewall.go
- pkg/server/cloud/gce/gce_functional_test.go
- pkg/server/cloud/gce/instances.go
- pkg/util/test_helpers.go
This needs additional changes in order to be incorporated in the build:
* Added to scripts/run_tests.sh
* Update the serviceAccount and roles used by travis-ci.com.  Allow both pushing to GCR and a select set of functionality to run GCE funcational tests.
> GCE functional test, functional tests delete security groups

- deploy/manifests/kip/overlays/minikube/README.md
- deploy/manifests/kip/overlays/minikube/kustomization.yaml
- deploy/manifests/kip/overlays/minikube/statefulset.yaml
- deploy/terraform-aws/cleanup-vpc.sh
- deploy/terraform-aws/env.tfvars.example
- deploy/terraform-aws/main.tf
- deploy/terraform-aws/outputs.tf
- deploy/terraform-aws/variables.tf
- deploy/terraform-gcp/env.tfvars.example
- deploy/terraform-gcp/main.tf
- deploy/terraform-gcp/variables.tf
- deploy/terraform-vpn/kustomization/kustomization.yaml.tmpl
- deploy/terraform-vpn/main.tf
- scripts/run_smoke_test.sh
It's never been a goal to reuse the Terraform examples, since they are pretty simplistic and intentionally ignore details that are important for a production grade setup. That being said, they are good for creating a new environment, quickly and without much hassle; so I refactored them here to ensure they can be used as modules, so the code can be used externally, via modules. The end goal is to be able to simply create a new AWS or GCP environment that we know works with Kip (I'd like to use it to set up an image test pipeline).
While testing the configs, I also bumped into an issue caused by 8ae8d723e544e3ee82a8b4d2ef6f22aca0c0ec1e, which broke terraform-vpn, so I also added a fix for that.
> Make sure TF configs can be used as modules

- pkg/util/instanceselector/instanceselector.go
- pkg/util/instanceselector/instanceselector_test.go
When creating an instance on GCP with `api.ResourceSpec{Memory: "0.5Gi", CPU: "1.0"}`, we get a custom type with 0.9GB memory: `instanceType: "n1-custom-1-921"`.
That comes from the script generating instance data: https://github.com/elotl/kip/blob/master/scripts/create_instance_data/create_gce_instance_data.py#L33
https://cloud.google.com/compute/docs/instances/creating-instance-with-custom-machine-type#n1_custom_machine_types says:
> For N1 machine types, select between 0.9 GB and 6.5 GB per vCPU, inclusive.
but apparently an additional requirement is that it _still_ needs to be a multiple of 0.25GB.
I added another check for the amount of memory when generating instance sizes, ensuring that it is a multiple of the base memory unit (0.25GB).
This fixes #171
> Fix memory calculation for custom instance types

- pkg/server/cloud/aws/security_groups.go
Based on #169, some of the fields in the `IpPermissions` struct might be nil. I went ahead and changed all pointer dereferences to use the `*Value()` helpers from the AWS SDK instead.
This fixes #169
> Fix nil pointer dereference in awsSGToMilpa()

- deploy/terraform-aws/main.tf
When finding an AZ, filter out local and any opt-in zones, otherwise we
might end up with a zone that does not support certain features (e.g.
mapping public IPs in Wavelength zones).
> Filter out opt-in AZs in terraform-aws

- pkg/server/pod_controller.go
- pkg/server/pod_controller_test.go
When iterating through images in the podspec, we need to make sure that:
1. We don't stop once the first ECR image is hit. In the podspec, there
might be multiple images in different regions that need ECR
credentials.
2. We take into account both regular containers and init containers.
> Ensure multiple ECR images can be pulled for a pod

- deploy/terraform-aws/cleanup-vpc.sh
The issue only seems to affect Terraform with the configuration updated to support Terraform 0.13+. See PR #200 for reference.
1. The security group deletion logic in a retry loop
2. The instance deletion has been simplified a little. Instead of querying instance without the shutting-down and terminate state, it grabs the instances with the pending and running state. Then it waits for the instances to be fully deleted before retrying the loop
3. Keep the output from awscli, since there’s information that’s useful when debugging
PR #200 depends in this PR.
> Fix race condition in cleanup-vpc.sh

- README.md
- deploy/terraform-aws/README.md
- deploy/terraform-aws/main.tf
- deploy/terraform-gcp/README.md
- deploy/terraform-gcp/main.tf
Still work in progress. I did AWS, and GCE will be next.
Closes #196
Update Terraform configuration files to support 0.13+. The maintainers have deprecated a few things like referencing external variables from a destroy provisioner.
> Change AWS terraform configuration to work with Terraform 0.13+

- deploy/terraform-aws/cleanup-vpc.sh
Because I quoted the variable instance_ids in the terminate-instance for loop, cleanup-vpc.sh doesn’t work with more than one instance. This PR fixes this by using a loop to properly expand the IDS.
I didn’t see this bug during my tests because I didn’t add any pod to the cluster.
Here’s the log of the error:
```
null_resource.gw (local-exec): An error occurred (InvalidInstanceID.Malformed) when calling the TerminateInstances operation: Invalid id: "i-026d5801edec31980
null_resource.gw (local-exec): i-0280cd2a27136b5ac"
null_resource.main (local-exec): An error occurred (InvalidInstanceID.Malformed) when calling the TerminateInstances operation: Invalid id: "i-026d5801edec31980
null_resource.main (local-exec): i-0280cd2a27136b5ac"
null_resource.gw (local-exec): Waiter InstanceTerminated …
```
> Fix my first bug: bad terminate-instances command

- Makefile
- deploy/terraform-aws/cleanup-vpc.sh
- pkg/certs/certs.go
Should fix #176 
Unfortunately I couldn’t reproduce the bug with go 1.13.
> Add SAN to client certificate to fix Kip built with 1.15 with EC2 instances.

- pkg/server/cloud/aws/instances.go
- pkg/server/nodemanager/node_controller.go
**Updates:**
- Add AZ targeting support when finding dedicated hosts
- Increase boot timeout so mac instances are not prematurely purged if they take a longer period of time to boot.
> Dedicated Host fixes

- deploy/manifests/kip/overlays/mac-tests/README.md
- deploy/manifests/kip/overlays/mac-tests/kustomization.yaml
- deploy/manifests/kip/overlays/mac-tests/provider.yaml
- deploy/manifests/kip/overlays/mac-tests/statefulset.yaml
This is a setup I've been using for e2e tests with mac1.metal. Probably we should wait with merging this one until we have other changes in kip & itzo merged, so we can use non-dev versions of those two.
> kustomize overlay for running mac workloads

- deploy/terraform-aws/node.sh
Probably the GPG key used for signing the k8s packages has changed.
Fetch and install the correct one before installing k8s packages.
> Fix apt key in terraform-aws

- deploy/terraform-aws/node.sh
- scripts/run_smoke_test.sh
Our `/terraform-aws` setup start failing due to the [docker bug](https://github.com/moby/moby/issues/41890). To fix it, I switched `docker.io` (which is no longer recommened package AFAIC) to `docker-ce` based on install instruction from [official docker docs](https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository). Also fixed deprecation warning about api version of`InitConfiguration` in `kubeadm init`.
> Fix kip smoke test: use docker-ce instead of docker.io in node.sh

- .travis.yml
- deploy/manifests/kip/base/sa.yaml
- scripts/init-cert/csr/csr.yaml
- scripts/init-cert/kubectl.sh
- scripts/run_smoke_test.sh
From EKS docs:
> The CertificateSigningRequest API has been promoted to stable certificates.k8s.io/v1 with the following changes:
spec.signerName is now required. You can't create requests for kubernetes.io/legacy-unknown with the certificates.k8s.io/v1 API.
You can continue to create CSRs with the kubernetes.io/legacy-unknown signer name with the certificates.k8s.io/v1beta1 API.
You can continue to request that a CSR to is signed for a non-node server cert, webhooks, for example, with the certificates.k8s.io/v1beta1 API. These CSRs aren't auto-approved.
I added `signerName: kubernetes.io/legacy-unknown`. Once kubernetes releases v1.22.0 we should consider switching to certificates.k8s.io/v1 API. 
Bumped Kubernetes version in the CI to v1.19.0 as well.
> add signerName to CSR - closes #235

- .travis.yml
- deploy/manifests/kip/overlays/aws-eks/kustomization.yaml
- deploy/manifests/kip/overlays/aws-eks/provider.yaml
- docs/running-in-eks.md
- scripts/eks-smoke-test/kip-nginx.yaml
- scripts/eks-smoke-test/regular-node-nginx.yaml
- scripts/run_eks_smoke_test.sh
EKS smoke tests scenario:
1. They run in our EKS elotl-ci-cd cluster.
2. We deploy newly built kip version there to `kip-smoke-tests` namespace and we taint a node, so only build jobs can run on it.
3. We deploy two nginx pods: one running on KIP, one on regular node.
4. We deploy another pod which curls those two.
5. If we get expected response, tests are complete.
Those test are meant to check if:
1. Kip starts in EKS cluster
2. KIP pods start successfully.
3. Connectivity between regular <-> kip and kip <-> kip pods
Added also a README with instructions for configuring EKS cluster for KIP.
If we keep `elotl-ci-cd` on Kubernetes version which is currently default for EKS, we can be sure that we support at least current default EKS version.
> Add EKS kustomize overlay and EKS smoke testing
